### ISSUE TITLE
https://github.com/EurekaEffect/zeon-crack

### ISSUE THREAD

**Issue by master7720** [ZeonDevelopment/Zeon#4]
https://github.com/EurekaEffect/zeon-crack
Its oldest version of CRYSTAL CL, but NOT ZEON, lmao

**Comment by EurekaEffect** [comment]
> https://github.com/EurekaEffect/zeon-crack Its oldest version of CRYSTAL CL, but NOT ZEON, lmao

1 month = oldest xdddd
also nothing changes

**Comment by EurekaEffect** [comment]
> https://github.com/EurekaEffect/zeon-crack Its oldest version of CRYSTAL CL, but NOT ZEON, lmao

retarded dev just rebranding his skid after crack/leak 😬
